### ISSUE TITLE
Is there an option to disable the "create new discussion" section 

### ISSUE THREAD

**Issue by alimat-nz** [dokufreaks/plugin-discussion#287]
Is there an option to disable the "create new discussion" section .

When I use 

{{threads>[:namespace]&[count=n]&[flags]&skipempty}}

I get a 

 New discussion page:

with a box to create it -> how do I stop this happening - I simply want to have a list of all discussions in progress listed.

Thanks

**Comment by alimat-nz** [comment]
I also note that if you try to use this field to create a new discussion it does not work and gives as error.

**Comment by LarsGit223** [comment]
There was an incompatibility with "Greebo" which should be fixed. But we haven't published a new release yet. Please re-install the plugin (even if there is no update message) and try again.

**Comment by alimat-nz** [comment]
I have re-installed as you suggested but it has not changed anything
Alistair Matthewamatthew@nz1.ibm.comIBM Services
 
 
----- Original message -----From: LarsGit223 <notifications@github.com>To: dokufreaks/plugin-discussion <plugin-discussion@noreply.github.com>Cc: alimat-nz <amatthew@nz1.ibm.com>, Author <author@noreply.github.com>Subject: Re: [dokufreaks/plugin-discussion] Is there an option to disable the "create new discussion" section (#287)Date: Mon, Feb 25, 2019 6:47 PM 
There was an incompatibility with "Greebo" which should be fixed. But we haven't published a new release yet. Please re-install the plugin (even if there is no update message) and try again.

**Comment by LarsGit223** [comment]
You still get that error if you click on "create a new discussion"? It doesn't change anything on the button section, it will still be there but the error shouldn't happen.

**Comment by alimat-nz** [comment]
ah - sorry I misunderstood what you had fixed. You are correct- I no longer get the error if I create a new discussion. What I was hoping for was that the 'create new discussion' was not displayed. DO you have any plans to make that an optional setting?
 
Thanks
Alistair Matthewamatthew@nz1.ibm.comIBM Services
 
 
----- Original message -----From: LarsGit223 <notifications@github.com>To: dokufreaks/plugin-discussion <plugin-discussion@noreply.github.com>Cc: alimat-nz <amatthew@nz1.ibm.com>, Author <author@noreply.github.com>Subject: Re: [dokufreaks/plugin-discussion] Is there an option to disable the "create new discussion" section (#287)Date: Wed, Feb 27, 2019 6:52 PM 
You still get that error if you click on "create a new discussion"? It doesn't change anything on the button section, it will still be there but the error shouldn't happen.

**Comment by LarsGit223** [comment]
Please re-install and test with appending the flag ```&nonewthreadform```. The _"New discussion page"_ button/formular should **not** be shown then.

(This is not released yet, so you will not see an update message in the extension manager)

**Comment by alimat-nz** [comment]
Many Thanks - That is exactly what I was looking for :)
Alistair MatthewIBM Services
 
 
----- Original message -----From: LarsGit223 <notifications@github.com>To: dokufreaks/plugin-discussion <plugin-discussion@noreply.github.com>Cc: alimat-nz <amatthew@nz1.ibm.com>, Author <author@noreply.github.com>Subject: Re: [dokufreaks/plugin-discussion] Is there an option to disable the "create new discussion" section (#287)Date: Fri, Mar 1, 2019 9:01 AM 
Please re-install and test with appending the flag &nonewthreadform. The "New discussion page" button/formular should not be shown then.
(This is not released yet, so you will not see an update message in the extension manager)

**Comment by Klap-in** [comment]
Implemented.
